//! SVG output of a validated diagram in one palette.
//!
//! Geometry (guides, connectors, card surfaces) is painted first and all text afterwards, so no line can cover a
//! glyph. Canvas text carries a canvas-colored halo. The output depends only on the diagram and the palette.

use std::fmt::Write as _;

use crate::{
    layout::{ACCENT_WIDTH, CORNER_RADIUS, LABEL_BASELINE, TEXT_INSET, detail_baseline, meta_baseline, title_baseline},
    model::{Anchor, Card, Connector, Diagram, Emphasis, Guide, Note, NoteStyle, Palette, Point, Section, Stroke},
    validate::{ValidationError, validate},
};

const SECTION_SUBTITLE_OFFSET: i32 = 22;
const SECTION_SUBTITLE_SPACING: i32 = 16;

/// Renders `diagram` with `palette` after validating it.
pub(crate) fn render(diagram: &Diagram, palette: &Palette) -> Result<String, ValidationError> {
    validate(diagram)?;
    let mut geometry = String::new();
    for guide in diagram.guides {
        write_guide(&mut geometry, guide);
    }
    for connector in diagram.connectors {
        write_connector_path(&mut geometry, connector);
    }
    for card in diagram.cards {
        write_card_surface(&mut geometry, card, palette);
    }
    let mut text = String::new();
    for section in diagram.sections {
        write_section(&mut text, section);
    }
    for connector in diagram.connectors {
        write_connector_label(&mut text, connector);
    }
    for card in diagram.cards {
        write_card_text(&mut text, card);
    }
    for note in diagram.notes {
        write_note(&mut text, note);
    }
    Ok(document(diagram, palette, &geometry, &text))
}

fn document(diagram: &Diagram, palette: &Palette, geometry: &str, text: &str) -> String {
    let Diagram { width, height, .. } = *diagram;
    let Palette {
        canvas, grid, frame, card, card_border, text: text_color, label, muted_text, guide, connector, ..
    } = *palette;
    let title = escape(diagram.title);
    let description = escape(diagram.description);
    format!(
        r#"<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title description" viewBox="0 0 {width} {height}">
  <title id="title">{title}</title>
  <desc id="description">{description}</desc>
  <metadata>Generated by crates/tools/how-it-works</metadata>
  <defs>
    <pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse">
      <path d="M24 0H0V24" fill="none" stroke="{grid}" stroke-width="1"/>
    </pattern>
    <marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">
      <path d="M1 1L9 5L1 9Z" fill="{connector}"/>
    </marker>
    <style>
      text {{ font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: {text_color}; }}
      .section-label, .box-label, .box-meta, .connector-label, .note-meta {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }}
      .section-label, .box-label {{ font-size: 12px; font-weight: 700; letter-spacing: 0.11em; fill: {label}; }}
      .section-subtitle {{ font-size: 12px; fill: {muted_text}; }}
      .guide {{ stroke: {guide}; stroke-width: 1; }}
      .connector {{ fill: none; stroke: {connector}; stroke-width: 1.9; stroke-linecap: round; }}
      .connector-label {{ font-size: 11px; font-weight: 700; fill: {connector}; }}
      .box {{ fill: {card}; stroke: {card_border}; stroke-width: 1.2; }}
      .box-title {{ font-size: 15px; font-weight: 700; }}
      .box-body {{ font-size: 12px; fill: {muted_text}; }}
      .box-meta {{ font-size: 11px; fill: {connector}; }}
      .note {{ font-size: 12px; fill: {muted_text}; }}
      .note-meta {{ font-size: 11px; font-weight: 700; letter-spacing: 0.08em; fill: {label}; }}
      .canvas-text {{ paint-order: stroke fill; stroke: {canvas}; stroke-width: 4px; stroke-linejoin: round; }}
    </style>
  </defs>
  <rect width="{width}" height="{height}" fill="{canvas}"/>
  <rect width="{width}" height="{height}" fill="url(#grid)"/>
  <rect x="0.5" y="0.5" width="{frame_width}" height="{frame_height}" fill="none" stroke="{frame}"/>
  {geometry}
  {text}
</svg>
"#,
        frame_width = width - 1,
        frame_height = height - 1,
    )
}

fn write_guide(output: &mut String, guide: &Guide) {
    let Guide { start: (x1, y1), end: (x2, y2) } = *guide;
    let _ = write!(output, r#"<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" class="guide"/>"#);
}

fn write_connector_path(output: &mut String, connector: &Connector) {
    let dash = if connector.stroke == Stroke::Dashed { r#" stroke-dasharray="7 7""# } else { "" };
    let marker = if connector.arrow { r#" marker-end="url(#arrow)""# } else { "" };
    let path = orthogonal_path(connector.points);
    let _ = write!(output, r#"<path d="{path}" class="connector"{dash}{marker}/>"#);
}

/// The SVG path of an orthogonal route whose interior corners become quadratic soft elbows.
fn orthogonal_path(points: &[Point]) -> String {
    let (first_x, first_y) = points[0];
    let mut path = format!("M{first_x} {first_y}");
    for index in 1..points.len() - 1 {
        let (previous, corner, following) = (points[index - 1], points[index], points[index + 1]);
        let radius = CORNER_RADIUS.min(distance(previous, corner) / 2).min(distance(corner, following) / 2);
        let (before_x, before_y) = towards(corner, previous, radius);
        let (after_x, after_y) = towards(corner, following, radius);
        let (corner_x, corner_y) = corner;
        let _ = write!(path, "L{before_x} {before_y}Q{corner_x} {corner_y} {after_x} {after_y}");
    }
    let (last_x, last_y) = points[points.len() - 1];
    let _ = write!(path, "L{last_x} {last_y}");
    path
}

fn distance(start: Point, end: Point) -> i32 {
    (end.0 - start.0).abs() + (end.1 - start.1).abs()
}

fn towards(start: Point, end: Point, distance: i32) -> Point {
    if start.0 == end.0 {
        (start.0, start.1 + (end.1 - start.1).signum() * distance)
    } else {
        (start.0 + (end.0 - start.0).signum() * distance, start.1)
    }
}

fn write_card_surface(output: &mut String, card: &Card, palette: &Palette) {
    let Card { x, y, width, height, .. } = *card;
    let accent = if card.emphasis == Emphasis::Primary { palette.primary } else { palette.secondary };
    let _ = write!(
        output,
        r#"<rect x="{x}" y="{y}" width="{width}" height="{height}" class="box"/><rect x="{x}" y="{y}" width="{ACCENT_WIDTH}" height="{height}" fill="{accent}"/>"#
    );
}

fn write_section(output: &mut String, section: &Section) {
    let Section { x, y, .. } = *section;
    let label = escape(&section.label.to_uppercase());
    let _ = write!(output, r#"<text x="{x}" y="{y}" class="section-label canvas-text">{label}</text>"#);
    for (line, offset) in section.subtitle.iter().zip((0..).map(|index| index * SECTION_SUBTITLE_SPACING)) {
        let baseline = y + SECTION_SUBTITLE_OFFSET + offset;
        let line = escape(line);
        let _ = write!(output, r#"<text x="{x}" y="{baseline}" class="section-subtitle canvas-text">{line}</text>"#);
    }
}

fn write_connector_label(output: &mut String, connector: &Connector) {
    if let Some(label) = connector.label {
        let (x, y) = label.position;
        let text = escape(&label.text.to_uppercase());
        let _ = write!(
            output,
            r#"<text x="{x}" y="{y}" text-anchor="middle" class="connector-label canvas-text">{text}</text>"#
        );
    }
}

fn write_card_text(output: &mut String, card: &Card) {
    let x = card.x + TEXT_INSET;
    if !card.label.is_empty() {
        let y = card.y + LABEL_BASELINE;
        let label = escape(&card.label.to_uppercase());
        let _ = write!(output, r#"<text x="{x}" y="{y}" class="box-label">{label}</text>"#);
    }
    let title_y = card.y + title_baseline(card);
    let title = escape(card.title);
    let _ = write!(output, r#"<text x="{x}" y="{title_y}" class="box-title">{title}</text>"#);
    for (index, line) in card.details.iter().enumerate() {
        let y = card.y + detail_baseline(card, index);
        let line = escape(line);
        let _ = write!(output, r#"<text x="{x}" y="{y}" class="box-body">{line}</text>"#);
    }
    for (index, line) in card.meta.iter().enumerate() {
        let y = card.y + meta_baseline(card, index);
        let line = escape(line);
        let _ = write!(output, r#"<text x="{x}" y="{y}" class="box-meta">{line}</text>"#);
    }
}

fn write_note(output: &mut String, note: &Note) {
    let Note { x, y, .. } = *note;
    let anchor = if note.anchor == Anchor::Middle { "middle" } else { "start" };
    let class = if note.style == NoteStyle::Meta { "note-meta" } else { "note" };
    let text = escape(note.text);
    let _ = write!(output, r#"<text x="{x}" y="{y}" text-anchor="{anchor}" class="{class} canvas-text">{text}</text>"#);
}

/// Escapes the five XML special characters.
fn escape(text: &str) -> String {
    let mut escaped = String::with_capacity(text.len());
    for character in text.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&#39;"),
            other => escaped.push(other),
        }
    }
    escaped
}

#[cfg(test)]
#[path = "../tests/unit/svg.rs"]
mod tests;
