//! Call timeline: packet priming, one output packet per input, drain and reset, and the quiet-intro calibration
//! boundary with the 5 s default. The numbers follow the Packet Timing Contract and Quiet-Intro Calibration sections
//! of `ARCHITECTURE.md`.

use crate::model::{
    Anchor, Card, Connector, ConnectorLabel, Diagram, Emphasis, Guide, Note, NoteStyle, Section, Stroke,
};

pub(crate) const DIAGRAM: Diagram = Diagram {
    slug: "call-timeline",
    title: "The timeline of one call",
    description: "A call starts with CallEnhancer::new. Packets 1 and 2 return Priming and produce no output. From \
                  packet 3 on, every packet returns one enhanced packet carrying the input of two packets earlier. \
                  Drain returns the two withheld packets, and reset starts the next call on the same instance. With \
                  the 5 s default, frames 0 to 310 are calibration frames that pass through un-enhanced while the \
                  noise is learned; frame 311, starting at 4.976 s, is the first enhanced frame.",
    width: 880,
    height: 684,
    sections: &[
        Section { label: "Packets · what the caller sees", subtitle: &[], x: 24, y: 44 },
        Section { label: "Calibration clock · 5-second default", subtitle: &[], x: 24, y: 452 },
    ],
    guides: &[Guide { start: (312, 40), end: (856, 40) }, Guide { start: (360, 448), end: (856, 448) }],
    connectors: &[
        Connector {
            points: &[(264, 132), (296, 132)],
            source: Some("new"),
            target: Some("priming"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(552, 132), (584, 132)],
            source: Some("priming"),
            target: Some("emitted"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(720, 196), (720, 264)],
            source: Some("emitted"),
            target: Some("drain"),
            label: Some(ConnectorLabel { text: "last packet", position: (774, 234) }),
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(584, 324), (552, 324)],
            source: Some("drain"),
            target: Some("reset"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(296, 324), (144, 324), (144, 196)],
            source: Some("reset"),
            target: Some("new"),
            label: Some(ConnectorLabel { text: "same instance", position: (220, 314) }),
            stroke: Stroke::Dashed,
            arrow: true,
        },
        Connector {
            points: &[(504, 536), (552, 536)],
            source: Some("calibrating"),
            target: Some("enhancing"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
    ],
    cards: &[
        Card {
            key: "new",
            label: "Call starts",
            title: "CallEnhancer::new",
            details: &["validates the configuration", "sizes every buffer once", "the only step that allocates"],
            meta: &[],
            x: 24,
            y: 68,
            width: 240,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "priming",
            label: "Packets 1 and 2",
            title: "Priming",
            details: &["no output yet: two packets", "are withheld (40 ms)"],
            meta: &["PacketOutcome::Priming"],
            x: 296,
            y: 68,
            width: 256,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "emitted",
            label: "Packet 3 onward",
            title: "One packet out per in",
            details: &["output n carries input n − 2"],
            meta: &["PacketOutcome::Emitted"],
            x: 584,
            y: 68,
            width: 272,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "drain",
            label: "End of call",
            title: "drain",
            details: &["returns the two withheld packets", "total output = total input"],
            meta: &["then StreamError::Drained"],
            x: 584,
            y: 264,
            width: 272,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "reset",
            label: "Next call",
            title: "reset",
            details: &["clears every stage in place", "restarts the calibration clock"],
            meta: &["no allocation"],
            x: 296,
            y: 264,
            width: 256,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "calibrating",
            label: "Frames 0–310",
            title: "Calibrating: learn the noise",
            details: &[
                "0 to 4.976 s: the estimator averages the power spectrum",
                "audio passes through, high-pass filtered only",
            ],
            meta: &["CallPhase::Calibrating"],
            x: 24,
            y: 472,
            width: 480,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "enhancing",
            label: "Frame 311 onward",
            title: "Enhancing",
            details: &["from 4.976 s: adaptive noise tracking", "Log-MMSE and tonal suppression"],
            meta: &["CallPhase::Enhancing"],
            x: 552,
            y: 472,
            width: 304,
            height: 128,
            emphasis: Emphasis::Primary,
        },
    ],
    notes: &[
        Note {
            text: "A frame is a calibration frame when it ends by 5 s: 128·t + 256 ≤ 40 000 samples.",
            x: 24,
            y: 632,
            anchor: Anchor::Start,
            style: NoteStyle::Plain,
        },
        Note {
            text: "Frame 311 starts at sample 39 808 (4.976 s). Not to scale: priming lasts 40 ms.",
            x: 24,
            y: 654,
            anchor: Anchor::Start,
            style: NoteStyle::Plain,
        },
    ],
};
