//! Processing flow: one packet's path through the stages of a call, in the order `CallEnhancer` runs them, and the
//! parallel model across calls.
//!
//! The seed follows the signal flow of `docs/algorithms.md` and the stage order of `CallEnhancer::process_frame`:
//! power spectrum, noise estimate, tonal detection on the original power, Log-MMSE, tonal gain, synthesis, encode.

use crate::model::{
    Anchor, Card, Connector, ConnectorLabel, Diagram, Emphasis, Guide, Note, NoteStyle, Section, Stroke,
};

pub(crate) const DIAGRAM: Diagram = Diagram {
    slug: "processing-flow",
    title: "How one call processes a packet",
    description: "Inside one call every stage runs in order on the caller's thread: mu-law decode, high-pass filter \
                  and the analysis buffer for each packet, then for each frame the power spectrum, the noise \
                  estimator in calibration or adaptive mode, the tonal detector on the original power, Log-MMSE with \
                  decision-directed SNR, the combined per-bin gains, synthesis, and mu-law encoding into the output \
                  queue. Calibration frames skip steps 6 to 8. Independent calls run in parallel, each with its own \
                  CallEnhancer and no shared state.",
    width: 880,
    height: 1116,
    sections: &[
        Section {
            label: "One call · every step runs in order on the caller's thread",
            subtitle: &["Steps 1–3 run for each 160-byte packet; steps 4–10 for each 256-sample frame, which a \
                         packet completes 0, 1 or 2 times."],
            x: 24,
            y: 40,
        },
        Section {
            label: "Across calls · independent calls run in parallel",
            subtitle: &[
                "Each call owns one CallEnhancer holding all of its state. Calls share no state, locks or atomics."
            ],
            x: 24,
            y: 940,
        },
    ],
    guides: &[Guide { start: (24, 916), end: (856, 916) }],
    connectors: &[
        Connector {
            points: &[(272, 150), (316, 150)],
            source: Some("decode"),
            target: Some("high-pass"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(564, 150), (608, 150)],
            source: Some("high-pass"),
            target: Some("analysis"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(732, 204), (732, 252)],
            source: Some("analysis"),
            target: Some("power"),
            label: Some(ConnectorLabel { text: "frame", position: (770, 232) }),
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(608, 316), (564, 316)],
            source: Some("power"),
            target: Some("noise"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(732, 380), (732, 436)],
            source: Some("power"),
            target: Some("tonal"),
            label: Some(ConnectorLabel { text: "original P", position: (792, 412) }),
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(440, 380), (440, 436)],
            source: Some("noise"),
            target: Some("log-mmse"),
            label: Some(ConnectorLabel { text: "noise N", position: (488, 412) }),
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(440, 556), (440, 612)],
            source: Some("log-mmse"),
            target: Some("combine"),
            label: Some(ConnectorLabel { text: "gain G", position: (484, 588) }),
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(732, 556), (732, 662), (564, 662)],
            source: Some("tonal"),
            target: Some("combine"),
            label: Some(ConnectorLabel { text: "tonal gain", position: (648, 652) }),
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(316, 662), (272, 662)],
            source: Some("combine"),
            target: Some("synthesis"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(316, 316), (48, 316), (48, 612)],
            source: Some("noise"),
            target: Some("synthesis"),
            label: Some(ConnectorLabel { text: "calibration frames", position: (182, 306) }),
            stroke: Stroke::Dashed,
            arrow: true,
        },
        Connector {
            points: &[(148, 720), (148, 776)],
            source: Some("synthesis"),
            target: Some("encode"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
        Connector {
            points: &[(272, 830), (316, 830)],
            source: Some("encode"),
            target: Some("output"),
            label: None,
            stroke: Stroke::Solid,
            arrow: true,
        },
    ],
    cards: &[
        Card {
            key: "decode",
            label: "1 · per packet",
            title: "μ-law decode",
            details: &["160 bytes → 160 samples"],
            meta: &[],
            x: 24,
            y: 96,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "high-pass",
            label: "2 · per packet",
            title: "High-pass filter",
            details: &["80 Hz, removes DC and rumble"],
            meta: &[],
            x: 316,
            y: 96,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "analysis",
            label: "3 · per packet",
            title: "Analysis buffer",
            details: &["releases a 256-sample frame", "every 128 samples"],
            meta: &[],
            x: 608,
            y: 96,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "power",
            label: "4 · per frame",
            title: "Power spectrum",
            details: &["Hann window, 256-point FFT", "P = |X|² in 129 bins"],
            meta: &[],
            x: 608,
            y: 252,
            width: 248,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "noise",
            label: "5 · per frame",
            title: "Noise estimator",
            details: &["calibration: averages P", "adaptive: SPP-MMSE, MCRA", "or minimum tracking"],
            meta: &[],
            x: 316,
            y: 252,
            width: 248,
            height: 128,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "tonal",
            label: "6 · if enabled",
            title: "Tonal detector",
            details: &["reads P before suppression", "scores beeps and whistles"],
            meta: &[],
            x: 608,
            y: 436,
            width: 248,
            height: 120,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "log-mmse",
            label: "7 · per frame",
            title: "Log-MMSE",
            details: &["decision-directed SNR", "gain per bin, floor −26 dB"],
            meta: &[],
            x: 316,
            y: 436,
            width: 248,
            height: 120,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "combine",
            label: "8 · per bin",
            title: "Combine the gains",
            details: &["X · G · tonal gain", "tonal gain within [0, 1]"],
            meta: &[],
            x: 316,
            y: 612,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "synthesis",
            label: "9 · per frame",
            title: "Synthesis",
            details: &["inverse FFT, overlap-add", "finalizes 128 samples"],
            meta: &[],
            x: 24,
            y: 612,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "encode",
            label: "10 · per frame",
            title: "μ-law encode, queue",
            details: &["bounded ring buffer of", "finished output bytes"],
            meta: &[],
            x: 24,
            y: 776,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "output",
            label: "Returned to the caller",
            title: "Enhanced packet",
            details: &["one per packet in, from packet 3", "40 ms behind its input"],
            meta: &[],
            x: 316,
            y: 776,
            width: 248,
            height: 108,
            emphasis: Emphasis::Secondary,
        },
        Card {
            key: "call-a",
            label: "Thread 1",
            title: "Call A",
            details: &["its own CallEnhancer", "runs steps 1–10 in order"],
            meta: &[],
            x: 24,
            y: 984,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "call-b",
            label: "Thread 2",
            title: "Call B",
            details: &["its own CallEnhancer", "runs steps 1–10 in order"],
            meta: &[],
            x: 316,
            y: 984,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
        Card {
            key: "call-n",
            label: "Any thread or task",
            title: "Call N",
            details: &["its own CallEnhancer", "runs steps 1–10 in order"],
            meta: &[],
            x: 608,
            y: 984,
            width: 248,
            height: 108,
            emphasis: Emphasis::Primary,
        },
    ],
    notes: &[
        Note { text: "Frames 0–310 of a 5 s", x: 64, y: 420, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "calibration skip steps", x: 64, y: 438, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "6–8: the audio passes", x: 64, y: 456, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "through un-enhanced.", x: 64, y: 474, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "Steps 6 and 7 are independent", x: 608, y: 812, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "inputs, combined per bin in", x: 608, y: 830, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "step 8. They run one after the", x: 608, y: 848, anchor: Anchor::Start, style: NoteStyle::Plain },
        Note { text: "other, not concurrently.", x: 608, y: 866, anchor: Anchor::Start, style: NoteStyle::Plain },
    ],
};
