use std::{fs, path::PathBuf};

use super::{ASSET_DIRECTORY, GUIDE_PATH, Staleness, day_path, night_path, render_all, staleness, write};
use crate::diagrams;

/// A scratch repository root under the system temporary directory, removed when dropped.
struct ScratchRoot(PathBuf);

impl ScratchRoot {
    fn new(name: &str) -> Self {
        let path = std::env::temp_dir().join(format!("how-it-works-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("the temporary directory is writable");
        Self(path)
    }
}

impl Drop for ScratchRoot {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

#[test]
fn rendering_is_deterministic() {
    let first = render_all().expect("shipped diagrams are valid");
    let second = render_all().expect("shipped diagrams are valid");
    assert_eq!(first, second);
    let paths: Vec<&str> = first.iter().map(|output| output.path.as_str()).collect();
    let mut sorted = paths.clone();
    sorted.sort_unstable();
    assert_eq!(paths, sorted, "outputs come in a stable order");
}

#[test]
fn the_guide_embeds_each_diagram_in_both_themes() {
    let outputs = render_all().expect("shipped diagrams are valid");
    let guide = &outputs.iter().find(|output| output.path == GUIDE_PATH).expect("the guide is generated").content;
    assert!(guide.starts_with("<!-- Generated by crates/tools/how-it-works."), "the guide says it is generated");
    for diagram in diagrams::ALL {
        let (day, night) = (day_path(diagram.slug), night_path(diagram.slug));
        assert!(outputs.iter().any(|output| output.path == day));
        assert!(outputs.iter().any(|output| output.path == night));
        let picture = format!(
            "<picture>\n  <source media=\"(prefers-color-scheme: dark)\" srcset=\"{night}\">\n  <img src=\"{day}\" \
             alt=\""
        );
        assert!(guide.contains(&picture), "{}", diagram.slug);
    }
}

#[test]
fn the_freshness_check_reports_differing_missing_and_unexpected_files() {
    let root = ScratchRoot::new("freshness");
    let outputs = render_all().expect("shipped diagrams are valid");
    let everything: Vec<String> = outputs.iter().map(|output| output.path.clone()).collect();
    assert_eq!(
        staleness(&root.0, &outputs).expect("readable"),
        Staleness { differing: everything, unexpected: vec![] }
    );

    assert_eq!(write(&root.0, &outputs).expect("writable"), outputs.len());
    assert!(staleness(&root.0, &outputs).expect("readable").is_current());
    assert_eq!(write(&root.0, &outputs).expect("writable"), 0, "current outputs are not rewritten");

    let edited = day_path("crate-map");
    fs::write(root.0.join(&edited), "edited by hand").expect("writable");
    fs::remove_file(root.0.join(GUIDE_PATH)).expect("removable");
    let leftover = format!("{ASSET_DIRECTORY}/retired-diagram.svg");
    fs::write(root.0.join(&leftover), "<svg/>").expect("writable");
    fs::write(root.0.join(ASSET_DIRECTORY).join(".DS_Store"), "").expect("writable");
    assert_eq!(
        staleness(&root.0, &outputs).expect("readable"),
        Staleness { differing: vec![GUIDE_PATH.to_owned(), edited], unexpected: vec![leftover] }
    );

    assert_eq!(write(&root.0, &outputs).expect("writable"), 3);
    assert!(staleness(&root.0, &outputs).expect("readable").is_current());
}
